<h1>Detailansicht Event</h1>
<?php
$form = $this->form;
$form->prepare();
?>
<?php echo $this->form()->openTag($form) ?>
    <dl class="zend_form">
        <?php // TODO // echo $this->formElementErrors($form->get('name')) ?>
        <dt><?php echo $this->formLabel($form->get('name')) ?></dt>
        <dd><?php echo $this->formInput($form->get('name')) ?></dd>
        <dt><?php echo $this->formLabel($form->get('value')) ?></dt>
        <dd><?php echo $this->formInput($form->get('value')) ?></dd>
        <dt><?php echo $this->formLabel($form->get('type')) ?></dt>
        <dd><?php echo $this->formInput($form->get('type')) ?></dd>
        <dt><?php echo $this->formLabel($form->get('start')) ?></dt>
        <dd><?php echo $this->formInput($form->get('start')) ?></dd>
        <dt><?php echo $this->formLabel($form->get('end')) ?></dt>
        <dd><?php echo $this->formRadio($form->get('end')) ?></dd>
        <dt><?php echo $this->formLabel($form->get('done')) ?></dt>
        <dd><?php echo $this->formRadio($form->get('done')) ?></dd>
        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>
        <dd><?php echo $this->formInput($form->get('submit')) ?></dd>
    </dl>
<?php echo $this->form()->closeTag() ?>
