<h1>Test</h1>
<h2>Einleitung</h2>
<p>
Willkommen ...
</p>
<h2>Szenario 1</h2>
<p>
<strong>Beschreibung</strong>:<br>
Loggen Sie sich mit mit den Zugangsdaten 'guest@jochen-bauer.net' und dem Passwort 
'geheim' am System an. Schalten Sie dann im Bad beide Lampen aus, in der Küche 
beide an und im Wohnzimmer die Lampe 1. Loggen Sie sich dann aus. 
<!-- 
Sie loggen sich mit den Zugangsdaten guest@jochen-bauer.net und dem Passwort geheim 
am System in der raumbasierten Ansicht an. Sie sehen den Startbildschirm!
Versuchen Sie nun alle Lampen in der Küche einzuschalten, im Wohnzimmer Lampe 1 ein- 
und Lampe 2 auszuschalten. Im Bad sollen beide Lampen aus sein. Nachdem Sie diesen 
Systemzustand erreicht haben, loggen Sie sich aus. Folgende Abbildung zeigt Ihnen den
Zielzustand des Systems:<br>
<img src="http://ehcserver.jochen-bauer.net/img/testimg/test1-ziel.png" alt="Ziel Test 1" />
-->
</p>

