<h1>Test</h1>
<h2>Einleitung</h2>
<p>
Willkommen! Wir freuen uns, dass Sie sich Zeit kurz Zeit nehmen, um uns bei der 
Forschung und Entwicklung im AAL-Umfeld zu unterstützen. Wir begrüßen es, falls Sie
ihre Gedanken während der Systemnutzung aussprechen - wir können diese somit später 
nochmals aufgreifen und darüber nachdenken.  
</p>
<h2>Szenario 'Gesundheitsdaten verstecken'</h2>
<p>
<strong>Beschreibung</strong>:<br>
Loggen Sie sich mit mit den Zugangsdaten 'guest@jochen-bauer.net' und dem Passwort 
'geheim' am System in der raumbasierten Sicht an. Ein Gast wird erwartet und dieser 
soll die Gesundheitsdaten nicht sehen - klappen Sie diese zu.  
</p>
<h2>Szenario 'Hilfe organisieren'</h2>
<p>
<strong>Beschreibung</strong>:<br>
Loggen Sie sich mit mit den Zugangsdaten 'guest@jochen-bauer.net' und dem Passwort 
'geheim' am System in der raumbasierten Sicht an. Sie wissen nicht, wie Sie mit der 
angezeigten Warnung umgehen sollen. Ermitteln Sie den Hinweistext durch das System
und die E-Mail-Adresse und die Telefonnummer, um die externe Unterstützung durch Experten
einzuholen.
</p>
<h2>Szenario 'Licht beim Frühstückszubereiten'</h2>
<p>
<strong>Beschreibung</strong>:<br>
Loggen Sie sich mit mit den Zugangsdaten 'guest@jochen-bauer.net' und dem Passwort 
'geheim' am System in der raumbasierten Sicht an. Schalten Sie dann im Bad beide Lampen aus, in der Küche 
beide an und im Wohnzimmer die Lampe 1 an. Loggen Sie sich dann aus. 
</p>

<h2>Szenario 'Licht bei der Vorbereitung zum Schlafengehen'</h2>
<p>
<strong>Beschreibung</strong>:<br>
Loggen Sie sich mit mit den Zugangsdaten 'guest@jochen-bauer.net' und dem Passwort 
'geheim' am System in der funktionsbasierten Sicht an. Schalten Sie dann im Bad beide Lampen an, in der Küche 
beide aus und im Wohnzimmer die Lampe 2 an. Loggen Sie sich dann aus. 
</p>

<h2>Szenario 'Lüften'</h2>
<p>
<strong>Beschreibung</strong>:<br>
Loggen Sie sich mit mit den Zugangsdaten 'guest@jochen-bauer.net' und dem Passwort 
'geheim' am System in der raumbasierten Sicht an. Oeffnen Sie alle Türen in der Küche
das Fenster im Wohnzimmer und die Temperatur auf 20 Grad im Wohnzimmer und der Küche.
Loggen Sie sich dann aus. 
</p>

<h2>Szenario 'Heizen'</h2>
<p>
<strong>Beschreibung</strong>:<br>
Loggen Sie sich mit mit den Zugangsdaten 'guest@jochen-bauer.net' und dem Passwort 
'geheim' am System in der funktionsbasierten Sicht an. Schliessen Sie alle Türen und Fenster,
setzen Sie für die Temperatur in Küche und Wohnzimmer den Wert 23. Loggen Sie sich dann aus. 
</p>

<h2>Fragen/Thesen</h2>
<p>
Raumbasierte Sicht ist angenehmer als Funktionsbasierte Sicht.<br>
Szenario 'Licht bei der Vorbereitung zum Schlafengehen' und Szenario 'Licht beim Frühstückszubereiten' erfordern 
genau die gleichen Schritte, das eine führt das System zum Zustand des anderen.<br>
</p>
<p>
Es ist hilfreich, dass der Zustand der Wohnung komplett in der Grafik dargestellt wird, da diese öfter zum Nachweis über den Erfolg
der Aktion genutzt wird, als die reale Wohnung oder die tabellarische Übersicht unterhalb der Wohnungsgrafik.<br>
</p>
<p>
Es ist angebracht, dass das Cockpit mit den Warnungen nicht klappbar ist, damit sicher keine überlesen werden.
</p>
<p>
Energie- und Verbrauchskomponenten werden noch vermisst. [oeffnen]
</p>
<p>
Es sollten mehr Gesundheitsdaten erhoben werden. [oeffnen]
</p>
<p>
Eine Verbindung zur elektronischen Patientenakte ist gewünscht.
</p> 
<p>
Die Klappfunktion ist wichtig, da stetiges Scrollen als unangenehm wahrgenommen wird.
</p>
<p>
Der Nutzer ist sich bewusst, dass solche Hinweistexte (Tooltips) existieren?
</p>
<p>
Die Hinweistexte, wenn man mit der Maus über dem Aktionselement ist, reichen aus.
</p>
<p>
Hinweistexte sollten expliziter genannt werden, etwa mit einem info-Icon.
</p>
<p>
Der telefonische Support wird am bevorzugtesten in Empfang genommen, lieber als das Schreiben einer E-Mail oder dem Lesen in der Dokumentation.
</p>
<p>
Es wird nur in den Raum eingetreten, wenn es unabdingbar ist, also zur Temperaturregelung und nicht zum Licht-Ein-Ausschalten.
</p>
<p>
Es ist wichtig und hilfreich, dass die Systemnutzung über mein bestehendes Lieblingsgerät (Handy, Fernseher, Tablet, Computer) ansteuerbar ist.
</p>
<p>
Was war gut, was war schlecht, was hat gefehlt?
</p>
