<?php 
use \Zend\Debug\Debug;

// collect data structures from database
$logMessages = array();
$healthMessages = array();
foreach($events as $event){
	if ($event->getType() == "message"){
		$logMessages[] = $event;
	}
	if ($event->getType() == "health"){
		$healthMessages[] = $event;
	}
}
?>
<!-- Startseite -->
<div class="row">
	<div class="span12">
    <p style="text-align: center;">
    <img src='<?php echo $this->basePath(); ?>/img/ehome-center-logo.png' alt="Bild Header E|Home-Center" />
    </p>
    </div>
</div>
<div class="hero-unit">
    <h1><?php echo sprintf("Willkommen!", '<span class="zf-green">', '</span>') ?></h1>
    <p>Mustermann, Musterweg 13, 12345 Musterstadt</p>
    <p>[<a class="show_hide" href="#" rel="#container">+/-</a>]</p>
    <div id="container">
    	<div id="background">
			<img alt="apartment_picture" src='<?php echo $this->basePath();?>/img/praterstr3.jpg'>
        </div>
            <div id="light_kitchen_one" class="light">
                    <img class="img_light" id="img_light_kitchen_one" alt="gluehbirne_aus" src=<?php
if ($lightoneKitchen) {
        echo $this->basePath() . '/img/gluehbirne_an.png';
} else {
        echo $this->basePath() . '/img/gluehbirne_aus.png';
}
                                ?> />
                        </div>
                        <div id="light_kitchen_two" class="light">
                    <img class="img_light" id="img_light_kitchen_two" alt="gluehbirne_aus" src=<?php
if ($lighttwoKitchen) {
        echo $this->basePath() . '/img/gluehbirne_an.png';
} else {
        echo $this->basePath() . '/img/gluehbirne_aus.png';
}
                                ?> />
                        </div>
            <div id="light_bathroom_one" class="light">
                    <img class="img_light" id="img_light_bathroom_one" alt="gluehbirne_aus" src=<?php
if ($lightoneBath) {
        echo $this->basePath() . '/img/gluehbirne_an.png';
} else {
    echo $this->basePath() . '/img/gluehbirne_aus.png';
}
                ?> />
            </div>
            <div id="light_bathroom_two" class="light">
                    <img class="img_light" id="img_light_bathroom_two" alt="gluehbirne_aus" src=<?php
if ($lighttwoBath) {
        echo $this->basePath() . '/img/gluehbirne_an.png';
} else {
    echo $this->basePath() . '/img/gluehbirne_aus.png';
}
                ?> />
            </div>
            <div id="light_living_one" class="light">
                    <img class="img_light" id="img_light_living_one" alt="gluehbirne_aus" src=<?php 
if ($lightoneLivingRoom) {
        echo $this->basePath() . '/img/gluehbirne_an.png';
} else {
        echo $this->basePath() . '/img/gluehbirne_aus.png';
}
                                ?> />
                        </div><!-- // light-living -->
                        <div id="light_living_two" class="light">
                    <img class="img_light" id="img_light_living_two" alt="gluehbirne_aus" src=<?php 
if ($lighttwoLivingRoom) {
        echo $this->basePath() . '/img/gluehbirne_an.png';
} else {
        echo $this->basePath() . '/img/gluehbirne_aus.png';
}
                                ?> />
                        </div><!-- // light-living -->
                </div><!-- // div container -->
</div><!-- // hero-unit -->
<hr>
<div class='row'>
	<div class='span8'>
    <h2>Cockpit</h2>
    <div style='float: left; padding-right: 16px;'><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()); ?>
    </div>
    <p>
    	Angemeldet als <?php echo $useremail; ?>
    </p>
    <p>
    	<a class='btn' href="<?php echo $this->url('home', array('action' => 'logout')); ?>">Ausloggen</a>
	</p>
    </div>
    <div class='span4'>
    	<h2>Hilfe</h2>
        <p>
        	Wir helfen Ihnen gerne:<br>
        	support@example.org und 01234-12345
        </p>
	</div>
</div>
<hr>
<div class='row'>
	<div class='span12'>
		<h2>Funktionen</h2>
		<p>[<a class="show_hide" href="#" rel="#functions">+/-</a>]</p>
    	<div id="functions">
		<table border="1px">
 <?php 
$functionsTable = array();
$functionsTableRowTitle = array("LichtEins", "LichtZwei");
$functionsTableColumnTitle = array("Küche", "Wohnzimmer", "Bad");
//             Kueche   Wohnzimmer  Bad
// LichtEins    Val      Val        Val
// LichtZwei	Val 	 Val        Val 
$roomsSize = sizeof($rooms);
$rowsSize = sizeof($functionsTableRowTitle);
for($i=0;$i<$rowsSize;$i++){
	if ($i == 0){ // write header
		echo "<tr>";
		echo "<th>Name</th>";
		echo "<th>" . $functionsTableColumnTitle[0] . "</th>";
		echo "<th>" . $functionsTableColumnTitle[1] . "</th>";
		echo "<th>" . $functionsTableColumnTitle[2] . "</th>";
		echo "</tr>";
	}
	echo "<tr>";
	echo "<td>";
	echo  $functionsTableRowTitle[$i];
	echo "</td>";
	$j = 0;
	foreach($rooms as $room){
		if ($i == 0 && $room->getName() == $functionsTableColumnTitle[0]){
			$valLightOneCellOne = $room->getLightone();  
			if ($valLightOneCellOne == "100"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AN</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelightone' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>AUS</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelightone' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		if ($i == 0 && $room->getName() == $functionsTableColumnTitle[1]){
			$valLightOneCellTwo = $room->getLightone();
			if ($valLightOneCellTwo == "100"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AN</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelightone' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>AUS</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelightone' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
				
			}
		}
		if ($i == 0 && $room->getName() == $functionsTableColumnTitle[2]){
			$valLightOneCellThree = $room->getLightone();
			if ($valLightOneCellThree == "100"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AN</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelightone' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>AUS</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelightone' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		if ($i == 1 && $room->getName() == $functionsTableColumnTitle[0]){
			$valLightTwoCellOne = $room->getLighttwo();
			if ($valLightTwoCellOne == "100"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AN</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelighttwo' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>AUS</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelighttwo' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		if ($i == 1 && $room->getName() == $functionsTableColumnTitle[1]){
			$valLightTwoCellTwo = $room->getLighttwo();
			if ($valLightTwoCellTwo == "100"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AN</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelighttwo' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>AUS</span> ";
                echo "<a href='" . $this->url('home', array('action' => 'togglelighttwo' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		if ($i == 1 && $room->getName() == $functionsTableColumnTitle[2]){
			$valLightTwoCellThree = $room->getLighttwo();
			if ($valLightTwoCellThree == "100"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AN</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelighttwo' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>AUS</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelighttwo' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		$j++;	
	}
	echo "</tr>";
}
echo "</table>";
?>
	</div>
	</div>
</div>
<hr>
<div class="row">
	<div class="span12">
    	<h2>Gesundheitsdaten</h2>
    	<p>[<a class="show_hide" href="#" rel="#health">+/-</a>]</p>
    	<div id='health'>
<?php 
foreach($healthMessages as $healthMessage){
        echo "<p>";
        echo $healthMessage->getName(); 
        echo "</p>";
}
?>
		</div>
	</div>
</div>
<hr>
<div class="row">
	<div class="span12">
		<h2>Systemnachrichten</h2>
		<p>[<a class="show_hide" href="#" rel="#messages">+/-</a>]</p>
		<div id='messages'>
<?php 
foreach($logMessages as $logMessage){
        echo "<p>";
        echo $logMessage->getName(); 
        echo "</p>";
}
?>
		</div>
	</div>
</div>
