<?php 
use \Zend\Debug\Debug;

// collect data structures from database
$logMessages = array();
$healthMessages = array();
$warningMessages = array();
foreach($events as $event){
	if ($event->getType() == "message"){
		$logMessages[] = $event;
	}
	if ($event->getType() == "message" && $event->getName() == 'Warnung'){
		$warningMessages[] = $event;
	}
	if ($event->getType() == "health"){
		$healthMessages[] = $event;
	}
}
?>
<!-- Startseite -->
<div class="row">
	<div class="span12">
    <p style="text-align: center;">
    <img src='<?php echo $this->basePath(); ?>/img/ehome-center-logo.png' alt="Bild Header E|Home-Center" />
    </p>
    </div>
</div>
<div class="hero-unit">
    <h1><?php echo sprintf("Willkommen!", '<span class="zf-green">', '</span>') ?></h1>
    <p>Mustermann, Musterweg 13, 12345 Musterstadt</p>
    <p>[<a class="show_hide" href="#" rel="#container">+/-</a>]</p>
    <div id="container">
    	<div id="background">
			<img alt="apartment_picture" src='<?php echo $this->basePath();?>/img/praterstr3.jpg'>
        </div>
            <div id="light_kitchen_one" class="light">
                    <img class="img_light" id="img_light_kitchen_one" alt="gluehbirne_aus" src=<?php
if ($lightoneKitchen) {
        echo $this->basePath() . '/img/gluehbirne_an.png';
} else {
        echo $this->basePath() . '/img/gluehbirne_aus.png';
}
                                ?> />
                        </div>
                        <div id="light_kitchen_two" class="light">
                    <img class="img_light" id="img_light_kitchen_two" alt="gluehbirne_aus" src=<?php
if ($lighttwoKitchen) {
        echo $this->basePath() . '/img/gluehbirne_an.png';
} else {
        echo $this->basePath() . '/img/gluehbirne_aus.png';
}
                                ?> />
                        </div>
            <div id="light_bathroom_one" class="light">
                    <img class="img_light" id="img_light_bathroom_one" alt="gluehbirne_aus" src=<?php
if ($lightoneBath) {
        echo $this->basePath() . '/img/gluehbirne_an.png';
} else {
    echo $this->basePath() . '/img/gluehbirne_aus.png';
}
                ?> />
            </div>
            <div id="light_bathroom_two" class="light">
                    <img class="img_light" id="img_light_bathroom_two" alt="gluehbirne_aus" src=<?php
if ($lighttwoBath) {
        echo $this->basePath() . '/img/gluehbirne_an.png';
} else {
    echo $this->basePath() . '/img/gluehbirne_aus.png';
}
                ?> />
            </div>
            <div id="light_living_one" class="light">
                    <img class="img_light" id="img_light_living_one" alt="gluehbirne_aus" src=<?php 
if ($lightoneLivingRoom) {
        echo $this->basePath() . '/img/gluehbirne_an.png';
} else {
        echo $this->basePath() . '/img/gluehbirne_aus.png';
}
                                ?> />
                        </div><!-- // light-living -->
                        <div id="light_living_two" class="light">
                    <img class="img_light" id="img_light_living_two" alt="gluehbirne_aus" src=<?php 
if ($lighttwoLivingRoom) {
        echo $this->basePath() . '/img/gluehbirne_an.png';
} else {
        echo $this->basePath() . '/img/gluehbirne_aus.png';
}
                                ?> />
                        </div><!-- // light-living -->
                </div><!-- // div container -->
</div><!-- // hero-unit -->
<hr>
<div class='row'>
	<div class='span4'>
		<h2>Cockpit</h2>
		<div style='float: left; padding-right: 16px;'><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()); ?>
    </div>
		<p>
    	Angemeldet als <?php echo $useremail; ?>
    </p>
		<p>
			<a class='btn' href="<?php echo $this->url('home', array('action' => 'logout')); ?>">Ausloggen</a>
		</p>
	</div>
	<div class='span5'>
		<h2>Hinweise</h2>
<?php
echo "<ul>";	 
$openWarningMessagesCounter = 0;
foreach($warningMessages as $warningMessage){
	if ($warningMessage->getDone() == 1){
		continue;
	}
	echo "<li>";
    echo "<span style='color: red;'>" . $warningMessage->getName() . "</span>: ";
    echo $warningMessage->getValue() . "; ";
    echo "<a class='btn' href='" . $this->url('home', array('action' => 'togglemessage' , 'id' => $warningMessage->getId())) . "' title='Nachricht als zur Kenntnis genommen markieren und verstecken.'>x</a>";
	echo "</li>";
	$openWarningMessagesCounter++;
}
if ($openWarningMessagesCounter == 0){
	echo "<li>";
	echo "Alle Warnungen wurden gelesen und als erledigt markiert!";
	echo "</li>";
}
echo "</ul>"
?>
	</div>
	<div class='span3'>
		<h2>Hilfe</h2>
		<p>
			Wir helfen Ihnen gerne:<br> support@example.org und 01234-12345
		</p>
	</div>
</div>
<hr>
<div class='row'>
	<div class='span12'>
		<h2>Funktionen</h2>
		<p>[<a class="show_hide" href="#" rel="#functions">+/-</a>]</p>
    	<div id="functions">
		<table border="1px">
 <?php 
$functionsTable = array();
$functionsTableRowTitle = array("Licht Eins", "Licht Zwei", "Temperatur", "Luftfeuchtigkeit", "Fenster", "Türe");
$functionsTableColumnTitle = array("Küche", "Wohnzimmer", "Bad");
//             Kueche   Wohnzimmer  Bad
// LichtEins    Val      Val        Val
// LichtZwei	Val 	 Val        Val 
$roomsSize = sizeof($rooms);
$rowsSize = sizeof($functionsTableRowTitle);
for($i=0;$i<$rowsSize;$i++){
	if ($i == 0){ // write header
		echo "<tr>";
		echo "<th>Name</th>";
		echo "<th>" . $functionsTableColumnTitle[0] . "</th>";
		echo "<th>" . $functionsTableColumnTitle[1] . "</th>";
		echo "<th>" . $functionsTableColumnTitle[2] . "</th>";
		echo "</tr>";
	}
	echo "<tr>";
	echo "<td>";
	echo  $functionsTableRowTitle[$i]; // cell with function name
	echo "</td>";
	$j = 0;
	foreach($rooms as $room){
		if ($i == 0 && $room->getName() == $functionsTableColumnTitle[0]){ // First Run -> first function;Licht Eins Room Kitchen
			$valLightOneCellOne = $room->getLightone();  
			if ($valLightOneCellOne == "100"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AN</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelightone' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>AUS</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelightone' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		if ($i == 0 && $room->getName() == $functionsTableColumnTitle[1]){ // Licht Eins Room Living
			$valLightOneCellTwo = $room->getLightone();
			if ($valLightOneCellTwo == "100"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AN</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelightone' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>AUS</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelightone' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
				
			}
		}
		if ($i == 0 && $room->getName() == $functionsTableColumnTitle[2]){ // Licht Eins Room Bath
			$valLightOneCellThree = $room->getLightone();
			if ($valLightOneCellThree == "100"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AN</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelightone' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>AUS</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelightone' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		if ($i == 1 && $room->getName() == $functionsTableColumnTitle[0]){ // Second Run second function
			$valLightTwoCellOne = $room->getLighttwo();
			if ($valLightTwoCellOne == "100"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AN</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelighttwo' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>AUS</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelighttwo' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		if ($i == 1 && $room->getName() == $functionsTableColumnTitle[1]){
			$valLightTwoCellTwo = $room->getLighttwo();
			if ($valLightTwoCellTwo == "100"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AN</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelighttwo' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>AUS</span> ";
                echo "<a href='" . $this->url('home', array('action' => 'togglelighttwo' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		if ($i == 1 && $room->getName() == $functionsTableColumnTitle[2]){
			$valLightTwoCellThree = $room->getLighttwo();
			if ($valLightTwoCellThree == "100"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AN</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelighttwo' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>AUS</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglelighttwo' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		if ($i == 2 && $room->getName() == $functionsTableColumnTitle[0]){ // Third Run Temp
			$tempCellOne = $room->getTemperature();
			echo "<td style='text-align: right;'>";
			echo $tempCellOne;
			echo " ";
			echo "<a href='" . $this->url('home', array('action' => 'editroom' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'>&raquo;</a>" . "</td>";
			echo "</td>";
		}
		if ($i == 2 && $room->getName() == $functionsTableColumnTitle[1]){
			$tempCellTwo = $room->getTemperature();
			echo "<td style='text-align: right;'>";
			echo $tempCellTwo;
			echo " ";
			echo "<a href='" . $this->url('home', array('action' => 'editroom' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'>&raquo;</a>" . "</td>";
			echo "</td>";
		}
		if ($i == 2 && $room->getName() == $functionsTableColumnTitle[2]){
			$tempCellThree = $room->getTemperature();
			echo "<td style='text-align: right;'>";
			echo $tempCellThree;
			echo " ";
			echo "<a href='" . $this->url('home', array('action' => 'editroom' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'>&raquo;</a>" . "</td>";
			echo "</td>";
		}
		if ($i == 3 && $room->getName() == $functionsTableColumnTitle[0]){ // Fourth Run second function
			$humidityTwoCellOne = $room->getHumidity();
			echo "<td style='text-align: right;'>";
			echo $humidityTwoCellOne;
			echo " ";
			echo "<a href='" . $this->url('home', array('action' => 'editroom' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'>&raquo;</a>" . "</td>";
			echo "</td>";
		}
		if ($i == 3 && $room->getName() == $functionsTableColumnTitle[1]){
			$humidityTwoCellTwo = $room->getHumidity();
			echo "<td style='text-align: right;'>";
			echo $humidityTwoCellTwo;
			echo " ";
			echo "<a href='" . $this->url('home', array('action' => 'editroom' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'>&raquo;</a>" . "</td>";
			echo "</td>";
		}
		if ($i == 3 && $room->getName() == $functionsTableColumnTitle[2]){
			$humidityTwoCellThree = $room->getHumidity();
			echo "<td style='text-align: right;'>";
			echo $humidityTwoCellThree;
			echo " ";
			echo "<a href='" . $this->url('home', array('action' => 'editroom' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'>&raquo;</a>" . "</td>";
			echo "</td>";
		}
		if ($i == 4 && $room->getName() == $functionsTableColumnTitle[0]){ // Second Run second function
			$windowTwoCellOne = $room->getWindow();
			if ($windowTwoCellOne == "1"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AUF</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglewindow' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>ZU</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglewindow' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		if ($i == 4 && $room->getName() == $functionsTableColumnTitle[1]){
			$windowTwoCellTwo = $room->getWindow();
			if ($windowTwoCellTwo == "1"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AUF</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglewindow' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>ZU</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglewindow' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		if ($i == 4 && $room->getName() == $functionsTableColumnTitle[2]){
			$windowTwoCellThree = $room->getWindow();
			if ($windowTwoCellThree == "1"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AUF</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglewindow' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>ZU</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'togglewindow' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		if ($i == 5 && $room->getName() == $functionsTableColumnTitle[0]){ // Second Run second function
			$doorCellOne = $room->getDoor();
			if ($doorCellOne == "1"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AUF</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'toggledoor' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>ZU</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'toggledoor' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		if ($i == 5 && $room->getName() == $functionsTableColumnTitle[1]){
			$doorCellTwo = $room->getDoor();
			if ($doorCellTwo == "1"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AUF</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'toggledoor' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>ZU</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'toggledoor' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		if ($i == 5 && $room->getName() == $functionsTableColumnTitle[2]){
			$doorCellThree = $room->getDoor();
			if ($doorCellThree == "1"){
				echo "<td style='text-align: right;'>";
				echo "<span style='color:orange;'>AUF</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'toggledoor' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			} else {
				echo "<td style='text-align: right;'>";
				echo "<span style='color:green;'>ZU</span> ";
				echo "<a href='" . $this->url('home', array('action' => 'toggledoor' , 'id' => $room->getId())) . "' title='Bearbeiten des Eintrags' class='btn btn-success'><></a>";
				echo "</td>";
			}
		}
		$j++;	
	}
	echo "</tr>";
}
echo "</table>";
?>
	</div>
	</div>
</div>
<hr>
<div class="row">
	<div class="span12">
		<h2>Gesundheitsdaten</h2>
		<p>
			[<a class="show_hide" href="#" rel="#health">+/-</a>]
		</p>
		<div id='health'>
		<!-- Sub containers -->
		<div class='row'>
                <div class='span6'>
                <?php 
echo "<table border='1px'>";
echo "<tr>";
echo "<!-- <th>ID</th> -->";
echo "<th>Datum</th>";
echo "<th>Uhrzeit</th>";
echo "<th>Meldung</th>";
echo "<th>Wert</th>";
echo "<th>Bemerkung</th>";
//echo "<th>ID</th>";
echo "</tr>";
$healthMessageCounter = 0;
$healthMessagesReversed = array_reverse($healthMessages);
foreach($healthMessagesReversed as $healthMessage){
		if ($healthMessageCounter > 5){
			continue;
		}
		echo "<tr>";
		echo "<td>";
		$date = new DateTime($healthMessage->getStart());
        echo $date->format('d.m.Y');
        echo "</td>";
        echo "<td>";
        $date = new DateTime($healthMessage->getStart());
        echo $date->format('h:m');
        echo "</td>";
		echo "<td>";
		echo $healthMessage->getName();
		echo "</td>";
		echo "<td>";
		echo $healthMessage->getValue();
		echo "</td>";
		echo "<td>";
		if ($healthMessage->getDone() == 1){
			echo "<span style='color: green;'>OK</span>";
		} else {
			echo "<span style='color: red;'>ACHTUNG</span>";
		}
		echo "</td>";
		//echo "<td>";
		//echo $healthMessage->getId();
		//echo "</td>";
		echo "</tr>";
		$healthMessageCounter++;
}
echo "</table>"
?>
                
                </div>              
                <div class='span6'>
        <!-- RGraph Lib // start -->
		<canvas id="weightGraph" width="500" height="150">[No canvas support]</canvas>
		<canvas id="pulseGraph" width="500" height="150">[No canvas support]</canvas>
		<script>
        window.onload = function()
        {
            var weightLine = new RGraph.Line('weightGraph', [82.4,82.8,82.6,82.2,82.0,79.3,79.6,79.1,78.2,78.9,77.3])
			.Set('title','Gewichtsentwicklung 2013')
            .Set('spline', true)
            .Set('numxticks', 0)
            .Set('numyticks', 0)
            .Set('hmargin', 10)
            .Set('background.grid.autofit.numvlines', 11)
            .Set('colors', ['orange'])
            .Set('linewidth', 5)
            .Set('gutter.left', 40)
            .Set('gutter.right', 15)
            .Set('labels',['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov'])
            .Set('shadow',true)
            .Set('shadow.color','#aaa')
            .Set('shadow.blur',5)
            .Draw();
            
            var pulseGraph = new RGraph.Line('pulseGraph', [65,68,66,61,68,72,66,63,66,68,69])
			.Set('title','Pulsentwicklung 2013')
            .Set('spline', true)
            .Set('numxticks', 0)
            .Set('numyticks', 0)
            .Set('hmargin', 10)
            .Set('background.grid.autofit.numvlines', 11)
            .Set('colors', ['orange'])
            .Set('linewidth', 5)
            .Set('gutter.left', 40)
            .Set('gutter.right', 15)
            .Set('labels',['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov'])
            .Set('shadow',true)
            .Set('shadow.color','#aaa')
            .Set('shadow.blur',5)
            .Draw();
        };
    	</script>
		<!-- RGraph Lib // end -->
                </div>
            </div>
		</div>
	</div>
</div>
<hr>
<div class="row">
	<div class="span12">
		<h2>Systemnachrichten</h2>
		<p>
			[<a class="show_hide" href="#" rel="#messages">+/-</a>]
		</p>
		<div id='messages'>
<?php 
$logMessagesReversed = array_reverse($logMessages);
echo "<ul>";
$logMessageCounter = 0;
foreach($logMessagesReversed as $logMessage){
		if($logMessageCounter > 8){
			continue;
		}
        echo "<li>";
        $date = new DateTime($logMessage->getStart());
        echo $date->format('d.m.Y');
        echo ", ";
        echo $date->format('h:m');
        echo "Uhr, ";
        echo $logMessage->getValue(); 
        echo "</li>";
        $logMessageCounter++;
}
echo "</ul>";
?>
		</div>
	</div>
</div>